config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  resources :tasks
  # get "/tasks", to: "tasks#index"
  # get "/tasks/new", to: "tasks#new", as: :new_task
  # post "/tasks", to: "tasks#create"
  # get "/tasks/:id", to: "tasks#show", as: :task
  # get "/tasks/:id/edit", to: "tasks#edit"
  # patch "/tasks/:id", to: "tasks#update"
  # delete "/tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(tasks_params)
    if @task.save
      redirect_to tasks_path, notice: "Task was successfully created"
    else
      render :new, status: :unprocessable_entity
    end
  end
  def edit
  end

  def update
    if @task.update(tasks_params)
      redirect_to task_path(@task), notice: "Task was successfully updated"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice: "Task was successfully deleted."
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def tasks_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails Task Manager" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <h1 class="d-flex justify-content-center">Task Manager</h1>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h2 class="text-center mt-5">Update this task</h2>

  <div class="row justify-content-center">
    <div class="col-md-5">
      <%= form_with(model: @task, method: :patch) do |form| %>
        <div class="form-group mb-3">
          <%= form.label :title %>
          <%= form.text_field :title, class: "form-control" %>
        </div>

        <div class="form-group mb-3">
          <%= form.label :details %>
          <%= form.text_area :details, class: "form-control" %>
        </div>

        <div class="form-group mb-3">
          <%= form.label :completed %>
          <%= form.check_box :completed, class: "ms-2" %>
        </div>

        <div class="d-flex justify-content-between align-items-center">
          <%= form.submit "Update Task", class: "btn btn-primary" %>
          <%= link_to "Back to list", tasks_path, class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>

app/views/tasks/index.html.erb
<div class="px-5">
  <%= link_to new_task_path, class: "text-decoration-none fs-5" do %>
  <i class="fa-solid fa-plus"></i>
    Add a new task
  <% end %>
</div>

<h2 class="d-flex justify-content-center mt-5">My tasks</h2>

<div class="d-flex justify-content-center mt-5">
 <div class="border px-5 p-3 rounded shadow">
   <ul>
  <% @tasks.each do |task| %>
    <li class="mt-3">
      <div>
        <input type="checkbox" <%= task.completed ? 'checked' : '' %>>
        <%= link_to task.title, task_path(task), class: "text-decoration-none" %> -
        <%= link_to '<i class="fa-solid fa-trash" style="color: #FF0000;"></i>'.html_safe, task_path(task), data: { turbo_method: :delete, turbo_confirm: "Delete #{task.title} ?" } %>
      </div>
    </li>
  <% end %>
  </ul>
 </div>
</div>

app/views/tasks/new.html.erb
<h2 class="text-center mt-5">Create a new task</h2>

  <div class="row justify-content-center">
    <div class="col-md-5">
      <%= form_with(model: @task) do |form| %>
        <div class="form-group mb-3">
          <%= form.label :title %>
          <%= form.text_field :title, class: "form-control" %>
        </div>

        <div class="form-group mb-3">
          <%= form.label :details %>
          <%= form.text_area :details, class: "form-control" %>
        </div>

        <div class="form-group mb-3">
          <%= form.label :completed %>
          <%= form.check_box :completed, class: "ms-2" %>
        </div>

        <div class="d-flex justify-content-between align-items-center">
          <%= form.submit "Create Task", class: "btn btn-primary" %>
          <%= link_to "Back to list", tasks_url, class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>

app/views/tasks/show.html.erb
<div class="px-5 text-primary">
  <%= link_to tasks_path, class: "text-decoration-none" do %>
    <i class="fa-solid fa-arrow-right fa-rotate-180"></i>
    Back to list
  <% end %>
</div>
<h2 class="d-flex justify-content-center mt-5"><%= @task.title %></h2>
<div>
  <div class="d-flex justify-content-center mt-5">
    <div class="border p-5 shadow rounded">
      <p><%= @task.details %></p>
      <div class="text-start mt-4">
        <%= link_to "Edit this task", edit_task_path(@task) %>
      </div>
    </div>
  </div>
</div>